Download Python, disable --onefile
- Downgrade from Python 3.14 to 3.12
- Change from onefile to folder

Earlier build had this size
    Directory: D:\a\wxpython_hello_world\wxpython_hello_world\dist

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            3/6/2026  2:45 AM       16172772 wxHelloWorld.exe
--- compressed size estimate ---
-a---            3/6/2026  2:45 AM       15964557 wxHelloWorld.zip

Earlier build had this error
Error: "Failed to load Python DLL 'C:\Users\ahz00\AppData\Local\Temp_MEI127322\python314.dll'. LoadLibrary: Invalid access to memory location."